# Generated by Django 6.1.1 on 2026-10-02 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=10, unique=True, verbose_name='Тег клана')),
                ('name', models.CharField(max_length=100, verbose_name='Название клана')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
            ],
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название танка')),
                ('tank_type', models.CharField(choices=[('HT', 'Тяжелый'), ('MT', 'Средний'), ('LT', 'Легкий'), ('TD', 'ПТ-САУ'), ('SPG', 'Арта')], max_length=50)),
                ('nation', models.CharField(max_length=50, verbose_name='Нация')),
                ('tier', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Уровень')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, unique=True, verbose_name='Никнейм')),
                ('battles', models.IntegerField(default=0, verbose_name='Кол-во боев')),
                ('wins', models.IntegerField(default=0, verbose_name='Побед')),
                ('clan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.clan', verbose_name='Клан')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название модуля')),
                ('module_type', models.CharField(choices=[('Engine', 'Двигатель'), ('Gun', 'Орудие'), ('Tracks', 'Ходовая')], max_length=50)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='api.tank', verbose_name='Танк')),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата боя')),
                ('damage', models.IntegerField(default=0, verbose_name='Урон')),
                ('is_victory', models.BooleanField(default=False, verbose_name='Победа')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.player', verbose_name='Игрок')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tank', verbose_name='Танк')),
            ],
        ),
    ]
